services:
  trainer:
    build: .
    container_name: house_price_trainer
    command: python main.py
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs

  fastapi:
    build: .
    container_name: house_price_api
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./src:/app/src
    depends_on:
      - trainer
